# -*- coding: utf-8 -*-
from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtMultimedia import QAudioOutput, QMediaPlayer
from PySide6.QtMultimediaWidgets import QVideoWidget
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QProgressBar, QSlider, QTextEdit, QVBoxLayout, QWidget

from .common import ActionButton, LOG_HEIGHT_OPEN, PREVIEW_HEIGHT_NORMAL
from .preview_canvas import PreviewCanvas

class CenterPanel(QFrame):
    def __init__(self, ui):
        super().__init__()
        self.setObjectName("CenterPanel")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)

        preview_shell = QFrame()
        preview_shell.setObjectName("PreviewShell")
        preview_layout = QVBoxLayout(preview_shell)
        preview_layout.setContentsMargins(12, 10, 12, 12)
        preview_layout.setSpacing(4)
        header = QHBoxLayout()
        title = QLabel("Preview")
        title.setObjectName("ColumnTitle")
        ui.preview_status = QLabel("Primeiro frame + sobreposições")
        ui.preview_status.setObjectName("Subtle")
        header.addWidget(title)
        header.addStretch(1)
        header.addWidget(ui.preview_status)
        preview_layout.addLayout(header)
        ui.preview = PreviewCanvas()
        ui.preview.positionChanged.connect(ui.apply_preview_drag_position)
        ui.video_player = QMediaPlayer(ui)
        ui.preview_audio = QAudioOutput(ui)
        ui.preview_audio.setVolume(1.0)
        ui.video_player.setAudioOutput(ui.preview_audio)
        ui.video_widget = QVideoWidget()
        ui.video_widget.setStyleSheet("background: #000000; border: none;")
        ui.video_player.setVideoOutput(ui.video_widget)
        ui.video_player.mediaStatusChanged.connect(ui.loop_preview_video)
        ui.video_widget.hide()

        ui.preview_group = QWidget()
        ui.preview_group.setObjectName("PreviewGroup")
        preview_group_layout = QVBoxLayout(ui.preview_group)
        preview_group_layout.setContentsMargins(0, 0, 0, 0)
        preview_group_layout.setSpacing(4)
        preview_group_layout.addWidget(ui.preview)
        preview_group_layout.addWidget(ui.video_widget)
        ui.set_preview_group_height(PREVIEW_HEIGHT_NORMAL)
        preview_layout.addStretch(1)
        volume_bar = QWidget()
        volume_bar.setObjectName("PreviewVolumeBar")
        volume_row = QHBoxLayout(volume_bar)
        volume_row.setContentsMargins(16, 0, 16, 0)
        volume_row.setSpacing(6)
        volume_row.addStretch(1)
        ui.preview_volume_label = QLabel("100%")
        ui.preview_volume_label.setObjectName("Subtle")
        ui.preview_volume_label.setFixedWidth(30)
        ui.preview_volume_label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        ui.preview_volume_slider = QSlider(Qt.Horizontal)
        ui.preview_volume_slider.setRange(0, 20)
        ui.preview_volume_slider.setValue(20)
        ui.preview_volume_slider.setFixedWidth(148)
        ui.preview_volume_slider.valueChanged.connect(ui.set_preview_volume)
        volume_row.addWidget(QLabel("Volume"))
        volume_row.addWidget(ui.preview_volume_slider)
        volume_row.addWidget(ui.preview_volume_label)
        preview_group_layout.addWidget(volume_bar)
        preview_layout.addWidget(ui.preview_group, 0, Qt.AlignHCenter)
        preview_layout.addStretch(1)
        layout.addWidget(preview_shell, 1)

        transport = QFrame()
        transport.setObjectName("Transport")
        transport_layout = QVBoxLayout(transport)
        transport_layout.setContentsMargins(12, 10, 12, 12)
        transport_layout.setSpacing(8)

        ui.lbl_status = QLabel("")
        ui.lbl_status.hide()
        ui.prog_bar = QProgressBar()
        ui.prog_bar.setRange(0, 100)
        ui.prog_bar.setValue(0)
        ui.prog_bar.setTextVisible(False)
        ui.prog_bar.setFixedHeight(14)
        transport_layout.addWidget(ui.prog_bar)

        buttons = QHBoxLayout()
        ui.btn_log = ActionButton("Mostrar log", "ghost")
        ui.btn_log.clicked.connect(ui.toggle_log)
        ui.btn_clear_log = ActionButton("Limpar log", "ghost")
        ui.btn_clear_log.clicked.connect(lambda: ui.log_widget.clear())
        ui.btn_pre_render = ActionButton("Preview", "normal")
        ui.btn_pre_render.clicked.connect(ui.pre_render_toggle)
        ui.btn_start = ActionButton("Exportar", "primary")
        ui.btn_start.clicked.connect(ui.export_toggle)
        ui.btn_cancel = ActionButton("Cancelar", "danger")
        ui.btn_cancel.setEnabled(False)
        ui.btn_cancel.setVisible(False)
        ui.btn_cancel.clicked.connect(ui.cancelar_render)
        buttons.addWidget(ui.btn_log)
        buttons.addWidget(ui.btn_clear_log)
        buttons.addStretch(1)
        buttons.addWidget(ui.btn_pre_render)
        buttons.addWidget(ui.btn_start)
        transport_layout.addLayout(buttons)

        ui.log_widget = QTextEdit()
        ui.log_widget.setReadOnly(True)
        ui.log_widget.setFixedHeight(LOG_HEIGHT_OPEN)
        ui.log_widget.hide()
        transport_layout.addWidget(ui.log_widget)
        layout.addWidget(transport)
